
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-manager
  namespace: honeypot
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: grafana-role
  namespace: honeypot
rules:
- verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - ''
  resources:
  - pods
  - pods/exec
  - pods/portforward
  - pods/proxy
- verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - ''
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - replicationcontrollers
  - replicationcontrollers/scale
  - secrets
  - serviceaccounts
  - services
  - services/proxy
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status

- verbs:
  - get
  - list
  apiGroups:
  - ''
  resources:
  - nodes
- verbs:
  - get
  - list
  - watch
  - update
  apiGroups:
  - ''
  resources:
  - namespaces
- verbs:
  - impersonate
  apiGroups:
  - ''
  resources:
  - serviceaccounts
- verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - apps
  resources:
  - deployments
  - deployments/rollback
  - deployments/scale
  - statefulsets
- verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
- verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  - scheduledjobs
- verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
- verbs:
  - create
  apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
- verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: RoleBinding
metadata:
  name: grafana-manager
  namespace: honeypot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-role
subjects:
  - kind: ServiceAccount
    name: grafana-manager
    namespace: honeypot
